name: "bulloak-toolchain"
description: "Install Bulloak and check that Solidity tests conform to BTT spec"
author: "Shubham Yadav"

branding:
  icon: "feather"
  color: "green"

inputs:
  cache:
    default: "true"
    description: "Whether to cache Cargo build"
    required: false
  skip-modifiers:
    default: "false"
    description: "Whether to ignore modifiers declaration in the Solidity test contracts"
    required: false
  test-dir:
    description: "The test directory"
    required: true
  version:
    default: "latest"
    description: "The version of Bulloak to install"
    required: false

outputs:
  bulloak-version:
    description: "Version as reported by `bulloak --version`"
    value: ${{steps.version.outputs.bulloak-version}}

runs:
  using: "composite"
  steps:
    - name: "Install Rust"
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache: false # Caching separately in the next step
        toolchain: stable

    - id: cache-cargo
      name: "Cache Cargo lockfile"
      if: ${{ inputs.cache == 'true' }}
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-cargo-${{ inputs.version }}-${{ hashFiles('**/Cargo.lock') }}
        path: ~/.cargo/bin/bulloak
        restore-keys: ${{ runner.os }}-cargo-${{ inputs.version }}-

    - name: "Install cargo-binstall"
      if: steps.cache-cargo.outputs.cache-hit != 'true'
      uses: cargo-bins/cargo-binstall@main

    - name: "Install bulloak"
      if: steps.cache-cargo.outputs.cache-hit != 'true'
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        DOCS_RS: "1"
      run: |
        if [ "$VERSION" == "latest" ]; then
          cargo binstall bulloak --no-confirm --log-level info
        else
          cargo binstall bulloak --version "$VERSION" --no-confirm --log-level info
        fi

    - id: "version"
      name: "Print installed version"
      shell: bash
      run: |
        echo "bulloak-version=$(bulloak --version)" >> $GITHUB_OUTPUT
        bulloak --version

    - name: "Check that the Solidity tests conform to BTT spec"
      env:
        SKIP_MODIFIERS: ${{ inputs.skip-modifiers }}
        TEST_DIR: ${{ inputs.test-dir }}
      shell: bash
      run: |
        echo "🌳 Checking the Solidity tests using Bulloak"
        if [ "$SKIP_MODIFIERS" == "true" ]; then
          find $TEST_DIR -name "*.tree" -print0 | xargs -0 -I {} sh -c 'bulloak check "{}" --skip-modifiers'
        else
          find $TEST_DIR -name "*.tree" -print0 | xargs -0 -I {} sh -c 'bulloak check "{}"'
        fi
