name: "ci"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install and run Bulloak"
        uses: "smol-ninja/bulloak-toolchain@staging"
        with:
          test-dir: test-workspace

      - name: "Bulloak summary"
        run: |
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
