name: "ci"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install and run Bulloak"
        uses: "smol-ninja/bulloak-toolchain@main"
        with:
          tree-path: "test-workspace/**.tree"

      - name: "Bulloak summary"
        run: |
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
